Comment some lines

diff --git a/.github/workflows/build_dockerfile_on_release.yml b/.github/workflows/build_dockerfile_on_release.yml
--- a/.github/workflows/build_dockerfile_on_release.yml
+++ b/.github/workflows/build_dockerfile_on_release.yml
@@ -17,18 +17,18 @@ jobs:
        run: |
          curl -sL https://api.github.com/repos/sofstam/repo2/releases/latest | \
          jq -r ".tag_name" > latest-version.txt
-      - name: Check for modified files
-       id: git-check
-       run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
-      - name: Make new Dockerfile for latest release; commit
-        if: steps.git-check.outputs.modified == 'true'
-        run: |
-          REPO_VER=$(cat latest-version.txt | sed 's|v||')
-          # make new dir for new dockerfile; 
-          mkdir -pv environments/illumina/${REPO_VER}
-          cp -v * ${REPO_VER}
-           # have to stage new files or else they won't be commited; this doesn't fail if there is nothing new
-          git add ${REPO_VER}
-          git commit -am "New/Updated Dockerfile pangolin-designation ${REPO_VER}"
-          git push
+      # - name: Check for modified files
+      # id: git-check
+      # run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
+      # - name: Make new Dockerfile for latest release; commit
+      #  if: steps.git-check.outputs.modified == 'true'
+      #  run: |
+      #    REPO_VER=$(cat latest-version.txt | sed 's|v||')
+      #    # make new dir for new dockerfile; 
+      #    mkdir -pv environments/illumina/${REPO_VER}
+      #    cp -v * ${REPO_VER}
+      #     # have to stage new files or else they won't be commited; this doesn't fail if there is nothing new
+      #    git add ${REPO_VER}
+      #    git commit -am "New/Updated Dockerfile pangolin-designation ${REPO_VER}"
+      #    git push
         
